### ISSUE TITLE
Crash on debian, docker (probably AVX issue)

### ISSUE THREAD

**Issue by pacjo** [bonukai/MediaTracker#431]
I'm having trouble getting Mediatracker's docker container to work on my machine. Using latest doesn't provide any logs. Unstable (and the self built one) give `llegal instruction` and exit with code 132.

System info:
CPU: Core 2 Duo - E6750
OS: 5.10.120-1 (2022-06-09)

logs (unstable / self built):
```
PUID: 1000
PGID: 1000
Illegal instruction

PUID: 1000
PGID: 1000
Illegal instruction
```
(looping due to `restart: unless-stopped`)

compose:
```
version: "2.1"
services:
  mediatracker:
    image: bonukai/mediatracker:test
    container_name: mediatracker
    ports:
      - 7481:7481
    volumes:
      - /mnt/sdb1/docker/mediatracker/data:/storage
      - /mnt/sdb1/docker/mediatracker/assets:/assets
      - /mnt/sdb1/docker/mediatracker/logs:/logs
    environment:
      - PUID=1000
      - PGID=1000
#      - SERVER_LANG=en
#      - TMDB_LANG=en
#      - AUDIBLE_LANG=us
      - TZ=Europe/Warsaw
    restart: unless-stopped
```
