### ISSUE TITLE
docker-compose - conflicting options?

### ISSUE THREAD

**Issue by iraklis10** [bonukai/MediaTracker#487]
Excuse my ignorance but aren't these two assetsVolume conflicting?

```   
 volumes:
      - /home/YOUR_HOME_DIRECTORY/.config/mediatracker/data:/storage
      - assetsVolume:/assets

volumes:
  assetsVolume: null
```
