### ISSUE TITLE
Cannot Access Via Reverse Proxy

### ISSUE THREAD

**Issue by mathmaniac43** [bonukai/MediaTracker#54]
Hello,

I just found this tool, and really like the idea of it, so I have been working to set it up with my other self-hosted services. I use [Traefik 2.X](https://doc.traefik.io/traefik/) as a reverse proxy for all of my HTTP services, and perform redirects to force it to HTTPS. This works pretty seamlessly for my other services once I have the certificates in place, but attempting the same steps with MediaTracker, I consistently receive a 404 page not found error. I have resorted to accessing directly via HTTP on a separately-mapped port, bypassing Traefik altogether, which I would like to undo as soon as I can get it working through a proxy.

I am not proficient in TypeScript, so perhaps I am missing a setting or capability that already exists, but is there a way to configure MediaTracker to accept a redirect from a reverse proxy?

Thanks!

```yaml
networks:
    frontend:
        driver:     bridge
        internal:   false
        ipam:
            config:
                - subnet: 172.21.0.0/16

services:
    traefik:
        container_name: traefik
        image: traefik:v2.5.3
        restart: always
        networks:
            - frontend
        command:
            # Docker setup
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false
            - --providers.docker.network=frontend # Double-check that this is the actual name
            - --providers.file.directory=/configuration/
            - --providers.file.watch=true
            # Entrypoints
            - --entrypoints.entrypoint-http.address=:80
            - --entrypoints.entrypoint-https.address=:443
            # Global HTTP -> HTTPS Redirect
            - --entrypoints.entrypoint-http.http.redirections.entrypoint.to=entrypoint-https
            - --entrypoints.entrypoint-http.http.redirections.entrypoint.scheme=https
            # Enable dashboard
            - --api.dashboard=true
            # Enable logging
            - --log.filepath=/var/log/traefik.log
            - --log.level=ERROR
        labels:
            # Dashboard
            - traefik.enable=true
            - traefik.http.routers.router-traefik.rule=Host(`traefik`)
            - traefik.http.routers.router-traefik.entrypoints=entrypoint-https
            - traefik.http.routers.router-traefik.tls=true
            - traefik.http.routers.router-traefik.service=api@internal
        ports:
            - '80:80'                   # http
            - '443:443'                 # https
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./certs:/certificates:ro
            - ./generated/dyn-traefik.toml:/configuration/dyn-traefik.toml:ro # certificate paths specified here
            - ./volumes/traefik/logs:/var/log
    media-tracker:
        container_name: media-tracker
        image: bonukai/mediatracker:latest # @todo lock to specific version when available
        restart: always
        networks:
            - frontend  # Connect to routers and such for backup;
        depends_on:
            - traefik
        environment:
            LANG:           en
            TMDB_LANG:      us
            AUDIBLE_LANG:   us
        expose:
            - 7481 # expose http port via Traefik
        ports:
            - 7481:7481 # @todo this is for debugging only, and should be removed
        labels:
            - traefik.enable=true
            - traefik.http.routers.router-media-tracker.rule=Host(`media-tracker`)
            - traefik.http.routers.router-media-tracker.entrypoints=entrypoint-https
            - traefik.http.routers.router-media-tracker.tls=true
            - traefik.http.routers.router-media-tracker.service=service-media-tracker
            - traefik.http.services.service-media-tracker.loadbalancer.server.port=7481
        volumes:
            - ./volumes/media-tracker/assets:/assets # posters
            - ./volumes/media-tracker/storage:/storage
```
